//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrnekUygulama.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:urunservis", ConfigurationName="ServiceReference1.urunservisPortType")]
    public interface urunservisPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:urunservis#vtBaglan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string vtBaglan();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:urunservis#vtBaglan", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> vtBaglanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:urunservis#uyeDondur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OrnekUygulama.ServiceReference1.uyeListe uyeDondur();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:urunservis#uyeDondur", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OrnekUygulama.ServiceReference1.uyeListe> uyeDondurAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:urunservis#uyeKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string uyeKontrol(string isim);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:urunservis#uyeKontrol", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> uyeKontrolAsync(string isim);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urunservis")]
    public partial class uyeListe : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Uye uyeField;
        
        /// <remarks/>
        public Uye Uye {
            get {
                return this.uyeField;
            }
            set {
                this.uyeField = value;
                this.RaisePropertyChanged("Uye");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urunservis")]
    public partial class Uye : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adField;
        
        private string soyadField;
        
        private System.DateTime tarihField;
        
        /// <remarks/>
        public string ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
                this.RaisePropertyChanged("ad");
            }
        }
        
        /// <remarks/>
        public string soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
                this.RaisePropertyChanged("soyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
                this.RaisePropertyChanged("tarih");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface urunservisPortTypeChannel : OrnekUygulama.ServiceReference1.urunservisPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class urunservisPortTypeClient : System.ServiceModel.ClientBase<OrnekUygulama.ServiceReference1.urunservisPortType>, OrnekUygulama.ServiceReference1.urunservisPortType {
        
        public urunservisPortTypeClient() {
        }
        
        public urunservisPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public urunservisPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public urunservisPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public urunservisPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string vtBaglan() {
            return base.Channel.vtBaglan();
        }
        
        public System.Threading.Tasks.Task<string> vtBaglanAsync() {
            return base.Channel.vtBaglanAsync();
        }
        
        public OrnekUygulama.ServiceReference1.uyeListe uyeDondur() {
            return base.Channel.uyeDondur();
        }
        
        public System.Threading.Tasks.Task<OrnekUygulama.ServiceReference1.uyeListe> uyeDondurAsync() {
            return base.Channel.uyeDondurAsync();
        }
        
        public string uyeKontrol(string isim) {
            return base.Channel.uyeKontrol(isim);
        }
        
        public System.Threading.Tasks.Task<string> uyeKontrolAsync(string isim) {
            return base.Channel.uyeKontrolAsync(isim);
        }
    }
}
